### PR TITLE
RFC 6238 implementation and sample

### PR DESCRIPTION
**Pull request by DavidChristiansen**

### CODE REVIEW

**Comment by brockallen** [comment]
I think this PR is dead, no? It's quite out of sync now.

**Comment by DavidChristiansen** [comment]
Well it can be brought back in line. We never did catch up to go over it.  It's a good feature and implemented, so let's not throw it away

**Comment by brockallen** [comment]
Okies.

**Comment by amd989** [comment]
I have created a fork with the merge. Fork #688 So far, I only got 3 hard conflicts mainly with the readme, and resources.

I've been getting familiarized with this PR for a while, I have tested its functionality and seems to be working fine. No weird errors ATM.

The only thing I would add, is the ability to generate secrets based on a configuration property rather than hard-coded value, allowing secrets to be bigger if needed.

**Comment by DavidChristiansen** [comment]
@brockallen Things are in sync now - Over to you for final pull.

**Comment by DavidChristiansen** [comment]
Given that Brock has stated that he is no longer in a position to maintain MBR, I have taken the decision to merge this PR into Dev.  All compiles/green based on current head.

**Comment by DavidChristiansen** [comment]
Note: You may require to perform a DB migration to reflect schema changes to the UserAccount object.

**Pull request merged**
