### PR TITLE
Account Creation changes

### PR DESCRIPTION
**Pull request by christianacca**
Bug fixes and enhancements to code related to account creation

### CODE REVIEW

**Comment by brockallen** [comment]
Any tests to add, perhaps? :)

**Comment by christianacca** [comment]
No probs

**Comment by christianacca** [comment]
Brock, I've added some tests to the original commit. Plus another commit that adds `EmailVerifiedEvent.IsNewAccount` property.

I don't think I see any other changes on this PR so I'm going to merge to master tomorrow if that's OK with you?

Thanks
C

**Comment by brockallen** [comment]
you have the power!

**Comment by christianacca** [comment]
Cool :-)

**Comment by brockallen** [comment]
BTW, was this a breaking change?

**Comment by christianacca** [comment]
No breaking changes, just a tiny new feature. If you're following semver you would bump to 8.5.0...

**Comment by brockallen** [comment]
Ok, great. thanks.

**Pull request merged**
