### PR TITLE
Master

### PR DESCRIPTION
**Pull request by benleishman**
Small issue. Just changed MinimumNumberOfComplexityRules to minimumNumberOfComplexityRules so max complexity would be properly limited to 4.

### CODE REVIEW

**Comment by benleishman** [comment]
I think the GitHub desktop application has bugs. I'm only asking to merge the last commit not all 7. I think I'll go to the command line tools from now on.

**Comment by brockallen** [comment]
Hmm, which one of these was the one you wanted to submit?

**Comment by benleishman** [comment]
Just this commit: https://github.com/benleishman/BrockAllen.MembershipReboot/commit/3d868b472d9a9e3e4454fe3285d2e119d899cd1b

I believe MinimumNumberOfComplexityRules  should have a lower case M.

**Comment by brockallen** [comment]
Ah yes, certainly a bug. I'll fix it locally. Thanks

**Pull request closed without merging**
