### PR TITLE
Norwegian, Swedish and Danish translations for validation messages

### PR DESCRIPTION
**Pull request by girtsl**
Norwegian, Swedish and Danish translations for validation messages - courtesy of our client.

### CODE REVIEW

**Comment by brockallen** [comment]
Thanks - I finally got to them!

**Comment by christianacca** [comment]
I've just added batch files to build nuget packages for these satellite assemblies.

Maybe @girtsl can make a pull request with translated nuspec files? I'm thinking that the description tag should be in the target language. The nuspec files are located subfolders of the NuGet folder

**Comment by girtsl** [comment]
Sorry, I don't speak in any of the languages above - they were provided by our client. 
Also I'm not sure about the value of providing localized package metadata, but that's just my thoughts.

**Comment by ccrowhurstram** [comment]
OK no problem girtsl. I agree myself that it might be not that valuable to localize the *description* of these satellite nuget packages.

I know Microsoft does it, so was thinking it would be nice if MembershipReboot followed suite.

@brockallen, do you think it's worth localizing the nuget *metadata*?

**Comment by brockallen** [comment]
I'd skip it -- devs speak English (typically).

**Pull request merged**
