### PR TITLE
Bump to 9.0.0 for all projects

### LINKED ISSUE #693: NuGet package: MembershipReboot 9.0.0 does not fit MembershipReboot.Webhost 7.1.0
If I install the 9.0.0 NuGet version I get a TypeLoadException because the GetCurrentPrincipal does not exist in the WebHost package.
Instead it is named GetCurentPrincipal.

In the source code I see this was renamed a long time ago ?

Regards,

Geert Veenstra

### PR DESCRIPTION
**Pull request by tomascassidy**
Fixes #693

### CODE REVIEW

**Comment by brockallen** [comment]
Ack @christianacca about this

**Comment by ccrowhurstram** [comment]
Hi @tomascassidy, what's the motivation for bumping all the libraries? I'm sure there are good reasons, but technically I don't think it's required.

**Comment by tomascassidy** [comment]
There was a breaking change in the MembershipReboot package for 9.0.0 changing GetCurentPrincipal to GetCurrentPrincipal.  The other packages just need to be recompiled to be compatible with that naming change and bumping the version number seemed the easiest option.

The current situation is described in #693 where the MembershipReboot 9.0.0 package is not compatible with MembershipReboot.Webhost 7.1.0.

**Comment by brockallen** [comment]
Ah ok -- sorry, I had forgotten about the rename issue. I'll try to get these to nuget soon.

**Comment by apuchkov** [comment]
Just checking when BrockAllen.MembershipReboot.Ef version 9.0.0 nuget will be published. Thanks

**Comment by brockallen** [comment]
I think I just successfully pushed them -- please test? Thx

**Comment by apuchkov** [comment]
I see a new version on nuget. Thanks for a quick turnaround!

**Pull request merged**
